services:
  # Servicio de frontend (Angular)
  frontend:
    build:
      context: .  # Ruta a la carpeta de tu proyecto Angular
      dockerfile: Dockerfile
    container_name: medidas-front
    ports:
    - "4700:4700"  # Mapea el puerto 4700 del host al puerto 4700 del contenedor